export { AuthPage } from './auth-page'
export { MainPage } from './main-page'
export { MapPage } from './map-page'
export { NotFoundPage } from './not-found-page'
export { PlotsPage } from './plots-page'
